sonar.projectKey=pip3saavedra77_TuSuperFront
sonar.projectName=TuSuperFront
sonar.organization=pip3saavedra77
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,**/*.module.ts
sonar.sourceEncoding=UTF-8
