sonar.projectKey=Andreycho-B_tusuper-frontend
sonar.projectName=tusuper-frontend
sonar.organization=andreycho-b
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,**/*.module.ts
sonar.sourceEncoding=UTF-8
